insert 
	CERTIFICATION (CERTIFICATION_NAME, CERTIFICATION_DESC) 
values 
	('G', 'For all audiences'), 
	('PG', 'Parental Guidance Suggested (mainly for under 10s)'), 
	('PG-13', 'Parental Guidance Suggested for children under 13'), 
	('R', 'Under 17 not admitted without parent or guardian'),
	('NC-17', 'Under 17 not admitted'),
	('Approved',  'Pre-1968 titles only (from the MPAA site) Under the Hays Code, films were simply approved or disapproved based on whether they were deemed "moral" or "immoral".)');

insert 
	FILM_GENRE (FILM_GENRE_NAME, FILM_GENRE_DESC)
values
	('Action', 'Should contain numerous scenes where action is spectacular and usually destructive. Note: if a movie contains just one action scene (even if prolonged, e.g., airplane-accident) it does not qualify. Subjective.'),
	('Adult', 'Reserved for explicit works of consenting hardcore sex or sexual activity, or strong fetish material involving adults, specifically those created for the purposes of titillation or arousal. Must be used with the plot keywords of "hardcore" and "sex" or "special-sexual-interest". Documentaries about this type of material do not use the Adult genre. Subjective.'),
	('Adventure', 'Should contain numerous consecutive and inter-related scenes of characters participating in hazardous or exciting experiences for a specific goal. Not to be confused with Action, and should only sometimes be supplied with it. Subjective.'),
	('Animation', 'Over 75% of the title''s running time should have scenes that are wholly, or part-animated. Any form of animation is acceptable, e.g., hand-drawn, computer-generated, stop-motion, etc. Puppetry does not count as animation, unless a form of animation such as stop-motion is also applied. Incidental animated sequences should be indicated with the keywords part-animated or animated-sequence instead. Although the overwhelming majority of video games are a form of animation it''s okay to forgo this genre when adding them as this is implied by the title type. Objective.'),
	('Biography', 'Primary focus is on the depiction of activities and personality of a real person or persons, for some or all of their lifetime. Events in their life may be reenacted, or described in a documentary style. If re-enacted, they should generally follow reasonably close to the factual record, within the limitations of dramatic necessity. A real person in a fictional setting would not qualify a production for this genre. If the focus is primarily on events, rather than a person, use History instead. Objective.'),
	('Comedy', 'Virtually all scenes should contain characters participating in humorous or comedic experiences. The comedy can be exclusively for the viewer, at the expense of the characters in the title, or be shared with them. Please submit qualifying keywords to better describe the humor (i.e. spoof, parody, irony, slapstick, satire, black-comedy etc). If the title does not conform to the "virtually all scenes" guideline then please do not add the comedy genre; instead, submit the same keyword variations described above to signify the comedic elements of the title. Subjective.'),
	('Crime', '	Whether the protagonists or antagonists are criminals this should contain numerous consecutive and inter-related scenes of characters participating, aiding, abetting, and/or planning criminal behavior or experiences usually for an illicit goal. Not to be confused with Film-Noir, and only sometimes should be supplied with it. Subjective.'),
	('Documentary', 'Should contain numerous consecutive scenes of real personages and not characters portrayed by actors. This does not include fake or spoof documentaries, which should instead have the fake-documentary keyword. A documentary that includes actors re-creating events should include the keyword "reenactment" so that those actors are not treated as "Himself." This genre should also be applied to all instances of stand-up comedy and concert performances. Objective.'),
	('Drama', 'Should contain numerous consecutive scenes of characters portrayed to effect a serious narrative throughout the title. This can be exaggerated upon to produce melodrama. Subjective.'),
	('Family', 'Should be universally accepted viewing. e.g., aimed specifically for the education and/or entertainment of children or the entire family. Note: Usually, but not always, complementary to Animation. Objective.'),
	('Fantasy', 'Should contain numerous consecutive scenes of characters portrayed to effect a magical and/or mystical narrative throughout the title. Note: not to be confused with Sci-Fi which is not usually based in magic or mysticism. Subjective.'),
	('Film-Noir', 'Typically features dark, brooding characters, corruption, detectives, and the seedy side of the big city. Almost always shot in black and white, American, and set in contemporary times (relative to shooting date). We take the view that this genre began with Underworld (1927) and ended with Touch of Evil (1958). Note: neo-noir should be submitted as a keyword instead of this genre for titles that do not fit all criteria. Objective.'),
	('Game-Show', 'Competition, other than sports, between, usually, non-professional contestants. The competition can include a physical component, but is usually primarily mental or strategic as opposed to athletic. This also includes what are known as "quiz shows." Talent contests staged expressly for the program are considered Game-Shows. Objective.'),
	('History', 'Primary focus is on real-life events of historical significance featuring real-life characters (allowing for some artistic license); in current terms, the sort of thing that might be expected to dominate the front page of a national newspaper for at least a week; for older times, the sort of thing likely to be included in any major history book. While some characters, incidents, and dialog may be fictional, these should be relatively minor points used primarily to bridge gaps in the record. Use of actual persons in an otherwise fictional setting, or of historic events as a backdrop for a fictional story, would not qualify. If the focus is primarily on one person''s life and character, rather than events of historical scope, use Biography instead. Objective.'),
	('Horror', 'Should contain numerous consecutive scenes of characters effecting a terrifying and/or repugnant narrative throughout the title. Note: not to be confused with Thriller which is not usually based in fear or abhorrence. Subjective.'),
	('Musical', 'Should contain several scenes of characters bursting into song aimed at the viewer (this excludes songs performed for the enjoyment of other characters that may be viewing) while the rest of the time, usually but not exclusively, portraying a narrative that alludes to another Genre. Note: not to be added for titles that are simply music related or have music performances in them; e.g., pop concerts do not apply. Also, classical opera, since it is entirely musical, does not apply and should instead be treated as Music. Objective.'),
	('Music', 'Contains significant music-related elements while not actually being a Musical; this may mean a concert, or a story about a band (either fictional or documentary). Subjective.'),
	('Mystery', 'Should contain numerous inter-related scenes of one or more characters endeavoring to widen their knowledge of anything pertaining to themselves or others. Note: Usually, but not always associated with Crime. Subjective.'),
	('News', 'Reports and discussion of current events of public importance or interest. If the events are not current (at the time the title was initially released), use History instead. This generally includes newsreels, newsmagazines, daily news reports, and commentary/discussion programs that focus on news events. Objective.'),
	('Reality-TV', 'Features non-professionals in an unscripted, but generally staged or manipulated, situation. May or may not use hidden cameras; generally, but not always, in a non-studio setting. Objective.'),
	('Romance', 'Should contain numerous inter-related scenes of a character and their personal life with emphasis on emotional attachment or involvement with other characters, especially those characterized by a high level of purity and devotion. Note: Reminder, as with all genres if this does not describe the movie wholly, but only certain scenes or a subplot, then it should be submitted as a keyword instead. Subjective.'),
	('Sci-Fi', 'Numerous scenes, and/or the entire background for the setting of the narrative, should be based on speculative scientific discoveries or developments, environmental changes, space travel, or life on other planets. Subjective.'),
	('Short', 'Any theatrical film or made-for-video title with a running time of less than 45 minutes, i.e., 44 minutes or less, or any TV series or TV movie with a running time of less than 22 minutes, i.e. 21 minutes or less. (A "half-hour" television program should not be listed as a Short.) If known, please submit the running time if we do not have one on record. Objective.'),
	('Sport', 'Focus is on sports or a sporting event, either fictional or actual. This includes fictional stories focused on a particular sport or event, documentaries about sports, and television broadcasts of actual sporting events. In a fictional film, the sport itself can also be fictional, but it should be the primary focus of the film. Objective.'),
	('Talk-Show', 'Discussion or interviews of or with a series of guests or panelists, generally appearing as themselves in a non-fictional setting (though fictional programs that mimic the form are also included). (aka "chat show"). Objective.'),
	('Thriller', 'Should contain numerous sensational scenes or a narrative that is sensational or suspenseful. Note: not to be confused with Mystery or Horror, and should only sometimes be accompanied by one (or both). Subjective.'),
	('War', 'Should contain numerous scenes and/or a narrative that pertains to a real war (i.e., past or current). Note: for titles that portray fictional war, please submit it as a keyword only. Objective'),
	('Western', 'Should contain numerous scenes and/or a narrative where the portrayal is similar to that of frontier life in the American West during 1600s to contemporary times. Objective.');


insert 
	FILM (FILM_NAME, FILM_DESC, FILM_RELEASE_DATE, CERTIFICATION_ID, FILM_GENRE_ID, FILM_GROSS_SALES, FILM_BUDGET)
values	
	('Anchorman: The Legend of Ron Burgundy', 
	'Ron Burgundy is San Diego''s top-rated newsman in the male-dominated broadcasting of the 1970s, but that''s all about to change for Ron and his cronies when an ambitious woman is hired as a new anchor.',
	'2004-07-09',
	3,
	6,
	90600000,
	26000000),
	('The 40-Year-Old Virgin', 
	'Goaded by his buddies, a nerdy guy who''s never "done the deed" only finds the pressure mounting when he meets a single mother.',
	'2005-08-15',
	4,
	6,
	177400000,
	26000000),
	('The Shawshank Redemption', 
	'Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency.',
	'1994-10-14',
	4,
	9,
	58300000,
	25000000),
	('The Dark Knight', 
	'When the menace known as the Joker emerges from his mysterious past, he wreaks havoc and chaos on the people of Gotham, the Dark Knight must accept one of the greatest psychological and physical tests of his ability to fight injustice.',
	'2008-07-18',
	3,
	1,
	1005000000,
	185000000),
	('Fight Club', 
	'An insomniac office worker, looking for a way to change his life, crosses paths with a devil-may-care soap maker, forming an underground fight club that evolves into something much, much more.',
	'1999-10-15',
	4,
	9,
	100900000,
	63000000),
	('Forrest Gump', 
	'JFK, LBJ, Vietnam, Watergate, and other history unfold through the perspective of an Alabama man with an IQ of 75.',
	'1994-07-14',
	3,
	9,
	677900000,
	55000000),
	('Saving Private Ryan', 
	'Following the Normandy Landings, a group of U.S. soldiers go behind enemy lines to retrieve a paratrooper whose brothers have been killed in action.',
	'1998-07-24',
	4,
	9,
	481800000,
	70000000),
	('American History X', 
	'A former neo-nazi skinhead tries to prevent his younger brother from going down the same wrong path that he did.',
	'1998-11-20',
	4,
	9,
	23900000,
	20000000),
	('Wedding Crashers', 
	'John Beckwith and Jeremy Grey, a pair of committed womanizers who sneak into weddings to take advantage of the romantic tinge in the air, find themselves at odds with one another when John meets and falls for Claire Cleary.',
	'2005-07-15',
	4,
	6,
	285200000,
	40000000),
	('Zoolander', 
	'At the end of his career, a clueless fashion model is brainwashed to kill the Prime Minister of Malaysia.',
	'2001-09-28',
	3,
	6,
	60800000,
	28000000),
	('Dodgeball: A True Underdog Story', 
	'A group of misfits enter a Las Vegas dodgeball tournament in order to save their cherished local gym from the onslaught of a corporate health fitness chain.',
	'2004-06-18',
	3,
	6,
	167700000,
	20000000),
	('Star Wars: Episode I - The Phantom Menace',
	'Two Jedi Knights escape a hostile blockade to find allies and come across a young boy who may bring balance to the Force, but the long dormant Sith resurface to claim their old glory.',
	'1999-05-19',
	2,
	1,
	474500000,
	115000000),
	('The Matrix Reloaded',
	'Neo and the rebel leaders estimate that they have 72 hours until 250,000 probes discover Zion and destroy it and its inhabitants. During this, Neo must decide how he can save Trinity from a dark fate in his dreams.',
	'2003-05-15',
	4,
	1,
	281500000,
	150000000),
	('The Amazing Spider-Man',
	'After Peter Parker is bitten by a genetically altered spider, he gains newfound, spider-like powers and ventures out to solve the mystery of his parent''s mysterious death.',
	'2012-07-03',
	3,
	1,
	262000000,
	230000000),
	('Shrek 2',
	'Princess Fiona''s parents invite her and Shrek to dinner to celebrate her marriage. If only they knew the newlyweds were both ogres.',
	'2004-05-19',
	2,
	4,
	436500000,
	150000000),
	('The Passion of the Christ',
	'Depicts the final twelve hours in the life of Jesus of Nazareth, on the day of his crucifixion in Jerusalem.',
	'2004-02-25',
	4,
	9,
	370800000,
	30000000),
	('Transformers',
	'An ancient struggle between two Cybertronian races, the heroic Autobots and the evil Decepticons, comes to Earth, with a clue to the ultimate power held by a teenager.',
	'2007-07-03',
	3,
	1,
	319100000,
	150000000)

insert 
	ACTOR (ACTOR_FIRST_NAME, ACTOR_LAST_NAME, ACTOR_BIRTH_DATE)
values
	('Will', 'Ferrell', '1967-07-16'),
	('Christina', 'Applegate', '1971-11-25'),
	('Paul', 'Rudd', '1969-04-06'),
	('Steve', 'Carrell', '1962-08-16'),
	('David', 'Koechner', '1962-08-24'),
	('Seth', 'Rogan', '1982-04-15'),
	('Vince', 'Vaughn', '1970-03-28'),
	('Ben', 'Stiller', '1965-11-30'),
	('Catherine', 'Keener', '1959-03-23'),
	('Romany', 'Malco', '1968-11-18'),
	('Elizabeth', 'Banks', '1974-02-10'),
	('Leslie', 'Mann', '1972-03-26'),
	('Jane', 'Lynch', '1960-07-14'),
	('Jonah', 'Hill', '1983-12-20'),
	('Tim', 'Robbins', '1958-10-16'),
	('Morgan', 'Freeman', '1937-06-01'),
	('Bob', 'Gunton', '1945-11-15'),
	('Christian', 'Bale', '1974-01-30'),
	('Heath', 'Ledger', '1979-04-04'),
	('Aaron', 'Eckhart', '1968-03-12'),
	('Edward', 'Norton', '1969-08-18'),
	('Brad', 'Pitt', '1963-12-18'),
	('Meat', 'Loaf', '1947-09-27'),
	('Helena', 'Bonham Carter', '1966-05-26'),
	('Tom', 'Hanks', '1956-07-09'),
	('Sally', 'Field', '1946-11-06'),
	('Robin', 'Wright', '1966-04-08'),
	('Tom', 'Sizemore', '1961-11-29'),
	('Adam', 'Goldberg', '1970-10-25'),
	('Vin', 'Diesel', '1967-07-18'),
	('Matt', 'Damon', '1970-10-08'),
	('Ted', 'Danson', '1947-12-29'),
	('Edward', 'Furlong', '1977-08-02'),
	('Beverly', 'D''Angelo', '1951-11-15'),
	('Owen', 'Wilson', '1968-11-18'),
	('Christopher', 'Walken', '1943-03-31'),
	('Rachel', 'McAdams', '1978-11-17'),
	('Christine', 'Taylor', '1971-07-30'),
	('Jerry', 'Stiller', '1927-06-08'),
	('David', 'Duchovny', '1960-08-07'),
	('Rip', 'Torn', '1931-02-06'),
	('Liam', 'Neeson', '1952-06-07'),
	('Ewan', 'McGregor', '1971-03-31'),
	('Natalie', 'Portman', '1981-06-09'),
	('Ian', 'McDiarmid', '1944-08-11'),
	('Keanu', 'Reeves', '1964-09-02'),
	('Laurence', 'Fishburne', '1961-07-30'),
	('Carrie-Anne', 'Moss', '1967-08-21'),
	('Hugo', 'Weaving', '1960-04-04'),
	('Andrew', 'Garfield', '1983-08-20'),
	('Emma', 'Stone', '1988-11-06'),
	('Rhys', 'Ifans', '1967-07-22'),
	('Dennis', 'Leary', '1957-08-18'),
	('Martin', 'Sheen', '1940-08-03'),
	('Mike', 'Myers', '1963-05-25'),
	('Eddie', 'Murphy', '1961-04-03'),
	('Cameron', 'Diaz', '1972-08-30'),
	('Jim', 'Caviezel', '1968-09-26'),
	('Maia', 'Morgenstern', '1962-05-01'),
	('Christo', 'Jirkov', '1975-02-18'),
	('Shia', 'LeBeouf', '1986-06-11'),
	('Megan', 'Fox', '1986-05-16'),
	('Josh', 'Duhamel', '1972-11-14')

insert 
	ROLE (FILM_ID, ACTOR_ID, ROLE_NAME, ROLE_DESC, ROLE_FAMOUS_QUOTE)
values
	(1, 1, 'Ron Burgundy', 'A five-time (local) Emmy award-winning journalist, he is the main anchor for the KVWN Channel Four News Team from 1964 to 1977. Always confident and well-dressed, he is nevertheless ignorant, egotistical, misogynistic, narcissistic, and not very intelligent, but also remains the rock for the entire group. He develops an infatuation with newcomer Veronica Corningstone, initially having trouble wooing her with tried and true measures that allegedly won him many bimbo-type women in the past. He has a great fondness for a good glass of scotch whisky, poetry, and his best friend/pet dog Baxter, and plays a mean jazz flute. He refers to his fists as Jack Johnson and Tom O''Leary, calls his arms "guns", and is most definitely not afraid to resort to fisticuffs.', 'It''s so damn hot!  Milk was a bad choice'),
	(1, 2, 'Veronica Corningstone', 'She is an antagonist In Anchorman: The legend of Ron Burgundy and soon a protagonist in Anchorman 2: The legend continues. Veronica Corningstone is played by Christina Applegate ( Married with kids , Don''t tell mom the babysitter is dead)', ' Good evening, San Diego. I''m Veronica Corningstone. Tits McGee is on vacation.'),
	(1, 3, 'Brian Fantana', 'Brian Fantana is an anchorman and coworker of Ron Burgundy. He is known for being a ladies'' man (or at least trying to be) and is infamous for his "Sex Panther" cologne which he says is made from bits of real panther.', ' They''ve done studies, you know. 60% of the time, it works every time.'),
	(1, 4, 'Brick Tamland', 'Brick is Ron''s friend and the weatherman for the KVWN news team Brick appears to say irrelevant information, although has a good heart, he appears to be devoted but lacks intelligence having an I.Q. of 48 making him "mentally retarded".', 'I love lamp.'),
	(1, 5, 'Champ Kind', 'Champ comes across as the most masculine of the team due to his intense love of sports, signature catchphrase ("Whammy!") and sexist outlook on the workplace.', ' It is anchor*man*, not anchor*lady*. And that is a scientific fact.'),
	(1, 6, 'Eager Cameraman', 'Scottie, the field cameraman for Veronica Corningstone (Christina Applegate) when they file the report on the cat fashion show, and later at the panda birth.', null),
	(1, 7, 'Wes Mantooth', 'Wes is the lead anchor for the #2 news channel,the Evening News Team. He and Ron Burgundy have a bitter rivalry that has ensued verbally and physically. Towards the end of the film, Wes turned a new leaf and apologized to Ron and helped him up a ladder to escape the bears.', ' Dorothy Mantooth is a Saint!'),
	(1, 8, 'Arturo Mendez', 'Arturo Mendez is a character in Anchorman: The Legend of Ron Burgundy. He was the Anchorman of the Spanish Language News Team.', ' Tonight''s top story: The sewers run red with Burgundy''s blood.'),
	(2, 4, 'Andy', '', 'You know how when you grab a woman''s breast... it feels like... a bag of sand.'),
	(2, 9, 'Trish', '', ' I''m throwing myself at you and all you can think about are fucking toys.'),
	(2, 3, 'David', '', 'You know how I know you''re gay?  You like Coldplay.'),
	(2, 10, 'Jay', '', 'You''re putting the pussy on a pedestal.'),
	(2, 6, 'Cal', '', ' We went to Tijuana, Mexico, you know? And we thought it would be fun, you know, to go to a show. Everybody says you gotta check out one of these shows. And... it''s a woman fuckin'' a horse. We get there and we think it''s gonna be awesome and... it is not as cool as it sounds like it''s gonna be. It''s kinda gross.'),
	(2, 11, 'Beth', '', 'Ooh, you know where to shave me.'),
	(2, 12, 'Nicky', '', 'I''m starvin... let''s get some fuckin'' french toast!'),
	(2, 13, 'Paula', '', 'All right! That''s enough! Party''s over...  Let the virgin get back to work!'),
	(2, 14, 'eBay Customer', '', null),
	(3, 15, 'Andy Dufrense', 'Andy Dufresne (pronounced doo-FRAYN) served as vice president of a Portland, Maine bank before being erroneously convicted of the murder of his wife and her lover, a golf pro, and was sentenced to two life terms. He was sent to Shawshank Prison in 1947. Dufresne was the frequent target of sexual abuse from a prison clique known as the Sisters. His sage financial advice earned him protection from prison guards. Dufresne used his considerable intelligence and education to improve the prison library, which he named after former inmate and librarian Brooks Hatlen, and helped a number of convicts earn their high school diplomas. He also used his banking knowledge to start a money laundering scheme on behalf of prison warden Samuel Norton. In 1966 Dufresne attempted to win a new trial when fellow inmate Tommy Williams told the story of a former cellmate at another prison confessing to the murder of Dufresne''s wife and lover. Warden Norton squashed Dufresne''s hopes out of fear that Andy would inform authorities of the money laundering despite Andy''s promise to remain silent. After spending two months in an area of the prison known as "the hole", during which time Williams was assassinated, Dufresne escaped from Shawshank. He took documental evidence of the laundering scheme with him, which he would later mail to a Portland newspaper. Using the alias Randall Stevens (the name under the illegal accounts) Dufresne visited a number of Portland-area banks, withdrawing approximately p$370,000, money Norton intended to retire with. Dufresne buried some money in a hayfield near Buxton, Maine, at a location only known to his prison friend Ellis Boyd "Red" Redding, then fled to Zihuatanejo, Mexico, where he operated a hotel with charter fishing services for guests. Dufresne was later joined by Redding after Red was paroled and discovered the money Andy left for him in the Buxton hayfield. He finally was reunited with his friend in Mexico.', 'Remember Red, hope is a good thing, maybe the best of things, and no good thing ever dies.'),
	(3, 16, 'Ellis Boyd ''Red'' Redding', 'Convicted murderer Ellis Boyd Redding was sent to Shawshank Prison in Maine in 1927. He was given the nickname "Red" for his Irish heritage and as a play on his last name. Redding had a reputation for smuggling items into prison such as playing cards, whiskey, marijuana, and posters. Redding was denied parole in 1947 and 1957 despite pleas to the parole board that he had been rehabilitated. Redding was granted parole in 1967 even though he displayed callous indifference to the parole board; afterwards he lived in a halfway house and worked as a bagger at a grocery store. In keeping a promise to his friend, escaped inmate Andy Dufresne, Redding traveled to a hayfield near Buxton, Maine to unearth an item buried near an oak tree and rock wall. The item was a box containing money and an invitation to join Dufresne at his location undisclosed in the letter; Redding knew the site as Zihuatanejo, Mexico from an earlier conversation he had with Dufresne in the prison yard. Redding used the money for bus fare to Fort Hancock, Texas, en route to Zihuatanejo.', 'Andy Dufresne - who crawled through a river of shit and came out clean on the other side.'),
	(3, 17, 'Warden Norton', 'The Warden of Shawshank Prison. He believes in two things: discipline and the bible. Ironically, his interest in the bible manifests itself in selfish and evil ways. He takes advantage of his prisoners and is not incapable of having those who pose a threat murdered.', ' I believe in two things: discipline and the Bible. Here you''ll receive both. Put your trust in the Lord; your ass belongs to me. Welcome to Shawshank.'),
	(4, 18, 'Bruce Wayne', 'Bruce Wayne is the billionaire son of Thomas and Martha Wayne and CEO of Wayne Enterprises. He is also the secret identity of the crime-fighting Vigilante known as the Batman.', 'Sometimes the truth isn''t good enough, sometimes people deserve more. Sometimes people deserve to have their faith rewarded...'),
	(4, 19, 'Joker', 'Appearing to be the most evil, deranged, and flat out psychotic killer of all comic book villains, The Joker is the primary antagonist of Batman. He is the complete opposite of Batman, in everything from appearance (Batman tends to be a rather large and muscular man, while The Joker is typically a man of average height or even taller possessing a skinny frame), to ideals. The Joker views murder as sport, and will not hesitate to toy with his food before he eats it, even if said food are the men he has hired to work for him. As intimidating as he is psychotic, he still manages to recruit hordes of henchmen despite his maniacal insanity.', ' I don''t, I don''t want to kill you! What would I do without you? Go back to ripping off mob dealers? No, no, NO! No. You... you... complete me.'),
	(4, 20, 'Harvey Dent', 'Harvey Dent was Gotham City''s amiable and courteous district attorney and one of Batman''s strongest allies until Sal "Boss" Maroni threw acid in his face, hideously scarring him. It also fractured his mental state, causing him to become Two-Face, a schizoid criminal mastermind obsessed with duality and the number two.', 'You either die a hero or you live long enough to see yourself become the villain.'),
	(4, 16, 'Lucius Fox', 'Lucius Fox is a fictional character created by John Calnan, and first appeared in Batman #307 (January 1979). As a supporting character, he acts as Bruce Wayne''s business manager who supposedly unknowingly runs the business interests that supply Batman''s equipment needs as well as financing his operations.', ' Let me get this straight, you think that your client, one of the wealthiest and most powerful men in the world, is secretly a vigilante, who spends his nights beating criminals to a pulp with his bare hands, and your plan is to blackmail this person?'),
	(5, 21, 'The Narrator', 'Tells the story', ' Tyler sold his soap to department stores at $20 a bar. Lord knows what they charged. It was beautiful. We were selling rich women their own fat asses back to them.'),
	(5, 22, 'Tyler Durden', 'Mischief. Mayhem. Soap. The title line sums it up what he leaves out about himself. He is upset with the world the way it is and will not be satisfied until the world is back in primative times... Without hitting rock bottom there can be no evolution, no resurrection.', 'The things you own end up owning you.'),
	(5, 23, 'Robert ''Bob'' Paulsen', 'His name was Robert Paulson.', 'Go ahead, Cornelius, you can cry.'),
	(5, 24, 'Marla Singer', 'Marla Singer was a strong-willed woman who came across as being a complete nutcase.', ' My God. I haven''t been fucked like that since grade school.'),
	(6, 25, 'Forrest Gump', 'Forrest Gump grew up in Greenbow, Alabama and became good friends with Jenny Curran. They parted ways after college when Forrest joined the army. He gained and lost good friend Bubba and made a promise to him that he would start the shrimp business as that was Bubbas dream. He also gained friend Lieutenant Dan Taylor. He started servicing the US Army by playing Ping Pong. After that he made the shrimp business as a word to good ol'' Bubba. Dan Taylor joined him as First Mate but then made peace in the ocean. He made himself a millionare and did many great things.', 'Stupid is as stupid does.'),
	(6, 26, 'Mrs. Gump', 'Mrs. Gump was Forrest Gump''s momma in the movie Forrest Gump. Forrest describes his momma as a real smart lady. In the movie Mrs. Gump raises her son Forrest on her own after his daddy abandoned the family to which she explains to her son that his daddy went on vacation which is when you go somewhere and don''t ever come back.', ' Life''s a box of chocolates, Forrest. You never know what you''re gonna get.'),
	(6, 27, 'Jenny', 'Jennifer "Jenny" Curran Gump (July 16, 1945 - March 22, 1982) was Forrest Gump''s childhood friend, love interest, and later, wife.', ' Listen, you promise me something, OK? Just if you''re ever in trouble, don''t be brave. You just run, OK? Just run away.'),
	(7, 25, 'John H. Miller', 'Captain John H. Miller was a thirty year old American serving in the 2nd Rangers Battalion of the United States Army during World War Two, holding the rank of Captain and the protagonist of the film Saving Private Ryan. He was portrayed by actor Tom Hanks.', ' James, earn this... earn it.'),
	(7, 28, 'Mike Horvath', 'Technical Sergeant Michael "Mike" Horvath was an American soldier serving in the 2nd Rangers Battalion of the United States Army during World War Two who held the rank of Technical Sergeant. He was a close friend of Captain John H. Miller, and served with him in both Africa and Italy before the invasion of France. He was protrayed by actor Tom Sizemore. He served as the deuteragonist of the film Saving Private Ryan.', 'I don''t know. Part of me thinks the kid''s right. He asks what he''s done to deserve this. He wants to stay here, fine. Let''s leave him and go home. But then another part of me thinks, what if by some miracle we stay, then actually make it out of here. Someday we might look back on this and decide that saving Private Ryan was the one decent thing we were able to pull out of this whole godawful, shitty mess. Like you said, Captain, maybe we do that, we all earn the right to go home.'),
	(7, 29, 'Stanley Mellish', 'Private Stanley Mellish was a supporting character in the film, Saving Private Ryan. He was a Jewish-American soldier, and a member of Miller''s Squad during the later stages of World War Two. He had a strong dislike for the Nazis due to their public persecution and slaughter of the Jews.', 'Your father was circumcised by my rabbi, you prick!'),
	(7, 30, 'Adrian Caparzo', 'Private Adrian Caparzo was a supporting character in the film, Saving Private Ryan. He was one of the 7 Army Rangers handpicked by Captain Miller during the latter stages of World War Two to find Private James Francis Ryan. In the film, Saving Private Ryan, he was portrayed by actor Vin Diesel.', 'And another thing, every time you salute the Captain, you make him a target for the Germans. Do us a favor. Don''t do it. Especially when I''m standing next to him, capisci?'),
	(7, 31, 'James Francis Ryan', 'Private First Class James Francis Ryan is an American soldier who served for the 101st Airborne Division in Baker Company, 1st Battalion 506th PIR during World War Two. He was the youngest sibling of the Ryan family. His older brothers were Daniel Ryan, Peter Ryan and Sean Ryan and his mother was Margaret Ryan. He has a wife known as Mrs. Ryan. He serves as the pivotal character of the film, Saving Private Ryan.', 'You can tell her that when you found me, I was with the only brothers I had left. And that there was no way I was deserting them. I think she''d understand that.'),
	(7, 32, 'Fred Hamill', 'Captain Fred Hamill is the leader of a mixed group 101st Airborne Pathfinders Miller and his men met in Neuville, during World War Two. He and his team shot seven German Soldiers, who confronted Miller''s Men and some of his own paratroopers like Staff Sergeant Hill.', 'No, I mean it. Find him. Get him home.'),
	(8, 21, 'Derek Vinyard', 'Derek Vineyard begins in the movie as a troubled young man who due to his father''s racist views develops his own, to the point of leading a local Aryan Brotherhood/Neo Nazi group in beach side LA.', 'See this?  That means "Not welcome".'),
	(8, 33, 'Danny Vinyard', 'Danny emulates his older brother, adopting a skinhead mentality. He thinks nothing of confronting a group of black students in the school lavatory. When assigned to write a paper on a civil rights leader, Danny submits one about Adolf Hitler. His teacher turns to Dr. Sweeney (Avery Brooks), the principal, for help. Sweeney asks Danny to submit another report for their private seminar to be called American History X. The topic is to be his brother, Derek. Unknown to Danny, Sweeney has been visiting Derek in prison. Under his guidance, Derek has abandoned his radical views and now rejects hate groups. When he is released from prison, Derek is greeted as a hero by other members of the hate group, including their remote charismatic leader, Cameron (Stacy Keach). In a private meeting, Derek rejects Cameron and his neo-Nazi philosophy.', 'So I guess this is where I tell you what I learned - my conclusion, right? Well, my conclusion is: Hate is baggage. Life''s too short to be pissed off all the time. It''s just not worth it. Derek says it''s always good to end a paper with a quote. He says someone else has already said it best. So if you can''t top it, steal from them and go out strong. So I picked a guy I thought you''d like. "We are not enemies, but friends. We must not be enemies. Though passion may have strained, it must not break our bonds of affection. The mystic chords of memory will swell when again touched, as surely they will be, by the better angels of our nature."'),
	(8, 34, 'Doris Vinyard', 'Derek''s mother Doris invites Murray, whom she is dating, home for dinner, which turns into a full-blown argument between Derek and Murray, causing them to leave. That night, as Danny hears people attempting to steal Dennis'' truck, Derek shoots and kills one of the thieves and curb stomps another, before being arrested. He is sentenced to three years in prison for voluntary manslaughter.', 'You think you''re the only one doin'' time, Derek? You think you''re here all alone? You think I''m not in here with you?'),
	(9, 35, 'John Beckwith', 'John Beckwith (Owen Wilson) and Jeremy Grey (Vince Vaughn) are divorce mediators in Washington D.C. who "crash" wedding parties to meet and bed women.', 'You know how they say we only use 10 percent of our brains? I think we only use 10 percent of our hearts.'),
	(9, 7, 'Jeremy Grey', 'John Beckwith (Owen Wilson) and Jeremy Grey (Vince Vaughn) are divorce mediators in Washington D.C. who "crash" wedding parties to meet and bed women.', 'Yeah, it could have been the soft mattress. Or the midnight rape. Or the nude gay art show that took place in my room. One of those probably added to the lack of sleep.'),
	(9, 36, 'William Cleary', 'At the end of a season of successful crashes, Jeremy takes John to a wedding for the daughter of the U.S. Secretary of the Treasury, William Cleary (Christopher Walken).', 'Todd, that''s good! Tell that mean ocean!'),
	(9, 37, 'Claire Cleary', 'Meanwhile, John attempts to court Claire, the maid of honor, but is interrupted by her hotheaded boyfriend, Sack Lodge (Bradley Cooper), who is unfaithful and disrespectful behind her back. When Gloria invites Jeremy and John to an extended weekend party at their family compound, John overrules Jeremy to accept and get closer to Claire.', 'True love is your soul''s recognition of its counterpoint in another.'),
	(10, 8, 'Derek Zoolander', 'The self-absorbed and dim-witted but good-natured Derek Zoolander (Ben Stiller) is ousted as the top male fashion model by the rising star Hansel (Owen Wilson), and his reputation is further tarnished by a critical article from journalist Matilda Jeffries (Christine Taylor).', 'Rufus, Brint, and Meekus were like brothers to me. And when I say brother, I don''t mean, like, an actual brother, but I mean it like the way black people use it. Which is more meaningful I think. If there is anything that this horrible tragedy can teach us, it''s that a male model''s life is a precious, precious commodity. Just because we have chiseled abs and stunning features, it doesn''t mean that we too can''t not die in a freak gasoline fight accident.'),
	(10, 35, 'Hansel', 'The self-absorbed and dim-witted but good-natured Derek Zoolander (Ben Stiller) is ousted as the top male fashion model by the rising star Hansel (Owen Wilson), and his reputation is further tarnished by a critical article from journalist Matilda Jeffries (Christine Taylor).', 'I wasn''t like every other kid, you know, who dreams about being an astronaut, I was always more interested in what bark was made out of on a tree. Richard Gere''s a real hero of mine. Sting. Sting would be another person who''s a hero. The music he''s created over the years, I don''t really listen to it, but the fact that he''s making it, I respect that. I care desperately about what I do. Do I know what product I''m selling? No. Do I know what I''m doing today? No. But I''m here, and I''m gonna give it my best shot.'),
	(10, 38, 'Matilda Jeffries', 'The self-absorbed and dim-witted but good-natured Derek Zoolander (Ben Stiller) is ousted as the top male fashion model by the rising star Hansel (Owen Wilson), and his reputation is further tarnished by a critical article from journalist Matilda Jeffries (Christine Taylor).', 'Yeah, that too, but Derek, you saved the prime minister of Malaysia!'),
	(10, 1, 'Mugatu', 'Meanwhile, fashion mogul Jacobim Mugatu (Will Ferrell) and Derek''s agent Maury Ballstein (Jerry Stiller) are charged by the fashion industry with finding a model who can be brainwashed into assassinating the new progressive-leaning Prime Minister of Malaysia, allowing them to retain cheap child labor in the country. Though Mugatu has previously refused to work with Derek for any show, Derek accepts Mugatu''s offer to star in the next runway show.', 'It''s that damn Hansel! He''s so hot right now!'),
	(10, 39, 'Maury Ballstein', 'Meanwhile, fashion mogul Jacobim Mugatu (Will Ferrell) and Derek''s agent Maury Ballstein (Jerry Stiller) are charged by the fashion industry with finding a model who can be brainwashed into assassinating the new progressive-leaning Prime Minister of Malaysia, allowing them to retain cheap child labor in the country. Though Mugatu has previously refused to work with Derek for any show, Derek accepts Mugatu''s offer to star in the next runway show.', 'Mugatu is so hot right now he could take a crap, wrap it in tinfoil, put a couple fish hooks on it and sell it to Queen Elizabeth as earrings.'),
	(10, 40, 'J.P. Prewett', ' Matilda along with Derek find the anonymous caller is hand model J.P. Prewett (David Duchovny), who explains that the fashion industry has been behind several of history''s political assassinations, including Abraham Lincoln and John F. Kennedy and the brainwashed models are soon killed after they have completed their task.', 'The truth is male models have been assassinating world leaders for over 200 years. Abe Lincoln wanted to abolish slavery, right? Well, who do you think made the silk stockings and powdered wigs worn by our early leaders?'),
	(11, 7, 'Peter La Fleur', 'Peter LaFleur is the owner of Average Joe`s, a small gym with only a few members. When he defaults on the gym`s mortgage, it is purchased by his rival, the arrogant White Goodman, a fitness guru and owner of the Globo Gym across the street', ' I found that if you have a goal, that you might not reach it. But if you don''t have one, then you are never disappointed. And I gotta tell ya... it feels phenomenal.'),
	(11, 38, 'Kate Veatch', 'Attorney Katherine "Kate" Veatch is working on the transaction for White. White unsuccessfully attempts to seduce her and she instead develops a close friendship with Peter.', 'Hey! I''m not a lesbian.'),
	(11, 8, 'White Goodman', 'Peter LaFleur is the owner of Average Joe`s, a small gym with only a few members. When he defaults on the gym`s mortgage, it is purchased by his rival, the arrogant White Goodman, a fitness guru and owner of the Globo Gym across the street.', 'Oh, I don''t think I''m a lot dumber than you thought that I think that I thought that I was once.'),
	(11, 41, 'Patches O`Houlihan', ' They form a team with Peter and watch a 1950s-era training video narrated by dodgeball legend Patches O`Houlihan and a 12-year old boy named Timmy.', 'If you can dodge a wrench, you can dodge a ball.'),
	(12, 42, 'Qui-Gon Jinn', 'Considered by many to be one of the most atuned Jedi of the New Republic, Qui Gon Jinn was a venerable if maverick Jedi Master. He is a student of the living Force. Unlike other Jedi Masters, who solely lose themself in the meditation of the unifying Force, Qui-Gon Jinn also lived for the moment, espousing a philosophy of "feel, don''t think -- use your instincts." Were it not for Qui-Gon''s unruly views, he would have undoubtedly been on the Jedi Council.', 'There''s always a bigger fish.'),
	(12, 43, 'Obi-Wan Kenobi', 'Obi-Wan Kenobi is a Jedi Knight, and a major character in the Star Wars saga. He is one of only four characters; the others being Anakin Skywaker, C-3PO and R2-D2; who appears in all six films. Obi-Wan acts as a mentor to Anakin Skywalker and his son Luke Skywalker.', 'May the force be with you.  Always.'),
	(12, 44, 'Padme Amidala', 'Padme Naberrie was born on the planet Naboo to humble farmers. Her special gifts were recognized when she was little. At 12. she became a princess and at 14, she was elected to be Queen Amidala of Naboo. After serving 2 terms as Queen, she became Senator Padme Amidala.', 'I will not condone a course of action that will lead us to war.'),
	(12, 45, 'Emperor Palpatine', 'Palpatine was born on the Planet Naboo. Unknown to most, he is also a Sith Lord named Darth Sidious.  Palpatine represents the small, outer-rim planet Naboo in the Galactic Senate as a senator.', 'I am the Senate!'),
	(13, 46, 'Neo', 'Thomas A. "Tom" Anderson (alias Neo): Neo has carried since his inception the Matrix''s source code, known as the Prime Program. This gives him the ability to freely manipulate the simulated reality of the Matrix, similar to the authority a system administrator has over a given system. However, he mainly manifests these abilities as various superhuman powers.', 'I know Kung Fu.'),
	(13, 47, 'Morpheus', 'Morpheus is the captain of the Nebuchadnezzar, which is a hovercraft of the human forces of the last human city, Zion, in a devastated world where most humans are grown by sentient Machines and kept imprisoned in the Matrix, a virtual computer-generated world. Morpheus was once a human living inside the Matrix until he was freed earlier in life.', ' All of our lives, we have fought this war. Tonight I believe we can end it. Tonight is not an accident. There are no accidents. We have not come here by chance. I do not believe in chance. When I see three objectives, three captains, three ships. I do not see coincidence, I see providence. I see purpose. I believe it our fate to be here. It is our destiny. I believe this night holds for each and every one of us, the very meaning of our lives.'),
	(13, 48, 'Trinity', 'Like the series'' other principal characters, Trinity is a computer programmer and a hacker who has escaped from the Matrix, a sophisticated computer program in which most of the human race is imprisoned. Though few specifics are revealed about her previous life inside the Matrix, we are told that Morpheus, one of a number of real-world hovercraft commanders, initially identified her and helped her escape from the program. At the beginning of the series, she is first mate on Morpheus'' Nebuchadnezzar and serves mainly as a go-between for him and the individuals he wishes to free from the Matrix. As the series progresses, her primary importance as a character becomes her close relationship with Neo. She is skilled with computers, at operating vehicles both inside and outside the Matrix, and in martial arts.', ' You''re not going to lose me.  You feel this?  I''m never letting go.'),
	(13, 49, 'Agent Smith', 'Agent Smith is the main antagonist of the Matrix Trilogy, and is portrayed in all three films by Hugo Weaving. Initially conceived as a "starter villain" by the Wachowskis'', Smith was merely the first of many threats to be faced by Neo and his friends. However, Hugo Weaving''s performance of Smith became so iconic, the writer/directors decided to upgrade him to the role of primary antagonist for the remainder of the series.', ' We are here because of you, Mr Anderson. We''re here to take from you what you tried to take from us.  Purpose.'),
	(14, 50, 'Peter Parker/Spider-Man', 'Spider-Man made his first appearance in Amazing Fantasy #15, the last issue before cancellation. Due to his popularity, the web-spinning superhero got his own comic series not long after his introduction.  Spider-man is Peter Parker.  When he was in his final year of high school, Peter was touring the science lab of Columbia University. While there, an escaped spider fell upon Peter, biting him. Thus, the DNA strands of the spider were recombined with those of Peter, giving him the strength, speed, and agility of a spider.', 'Really? You seriously think I''m a cop? Cop in a skin-tight red and blue suit?'),
	(14, 51, 'Gwen Stacy', 'Gwen Stacy is Peter Parker''s girlfriend and Captain Stacy''s daughter.', 'Easy, Bug Boy.'),
	(14, 52, 'The Lizard/Dr. Curt Connors', 'In the original comic book continuity, Dr. Curt Connors became The Lizard whilst attempting to regenerate his missing arm. In the trilogy of films directed by Sam Raimi, he was a recurring character but did not transform, although it is rumoured Raimi wanted to introduce The Lizard in Spider-Man 4 but faced studio resistance. The Lizard appears in The Amazing Spider-Man, the reboot.', 'Poor Peter Parker. No father. No mother. No uncle. You''re all alone.'),
	(14, 53, 'Captain Stacy', 'Captain George Stacy is the works for the NYPD. He is a supporter of Spider-Man in the comics and a friend of Peter Parker.  In the upcoming The Amazing Spider-Man, Stacy is portrayed as against Spider-Man and thinks of him as an outlaw, much as J. Jonah Jameson thinks who is not shown in the movie. This approach is very different than that of the comics with George Stacy.', 'I was wrong about you, Peter. This city needs you. Here. You''re gonna need this. You''re gonna make enemies. People will get hurt. Sometimes the people closest to you. So I want you to promise me something, okay? Leave Gwen out of it. Promise me that. Huh? You promise me.'),
	(14, 54, 'Uncle Ben', 'Ben Parker is a loving uncle of Peter Parker.  Uncle Ben is a unique character in the world of comic book fiction. As he is the only character in the entire history of comic books to have died and actually have stayed dead. Giving way to a phrase known by many readers; "No one in comics stays dead except Uncle Ben".', 'Peter? I know things have been difficult lately and I''m sorry about that. I think I know what you''re feeling. Ever since you were a little boy, you''ve been living with so many unresolved things. Well, take it from an old man. Those things send us down a road... they make us who we are. And if anyone''s destined for greatness, it''s you, son. You owe the world your gifts. You just have to figure out how to use them and know that wherever they take you, we''ll always be here. So, come on home, Peter. You''re my hero... and I love you!'),
	(14, 26, 'Aunt May', 'May Parker is the loving aunt of Peter Parker and Ben''s wife.  She is a caring and gentle person who loves her family dearly.', 'Why didn''t you tell me you didn''t like my meat loaf? You could have said that to me 37 years ago.  How many meat loaves have I made for you?'),
	(15, 55, 'Shrek', 'Shrek is an ogre. He finds true love with Princess Fiona. He has baby kids.', 'Donkey, you HAVE the right to remain silent. What you lack is the capacity.'),
	(15, 56, 'Donkey', 'Donkey is the deuteragonist of the Shrek franchise. He is Shrek''s best friend, Dragon''s husband, and the Dronkeys'' father.', 'Oh, man! Where do I begin? First there was the time the farmer traded me for some magic beans. I ain''t never gotten over that. Then this fool went off and had a party, and they all starting trying to pin a tail on me. Then they all got drunk, and started hitting me with sticks, yelling "Piñata! Piñata!" What is a piñata, anyway?'),
	(15, 57, 'Princess Fiona', 'The princess turned love interest of Shrek, played by Cameron Diaz.', 'I want what any princess wants - to live happily ever after... with the *ogre* I married.'),
	(16, 58, 'Jesus Christ', 'Jesus Christ is Jesus of Nazareth, a rabbi, preacher, and Messiah who is the central figure of Christianity.', 'Forgive them, Father. They know not what they do.'),
	(16, 59, 'Mary', 'The mother of Christ', 'Flesh of my flesh... Heart of my heart... My son, let me die with you.'),
	(16, 60, 'Joseph', 'Jesus'' most steadfast discipline in the time of Christ.', 'Master, what has happened to you? Should I call the other Lord?'),
	(17, 61, 'Sam Witwicky', 'Samuel James "Sam" Witwicky is portrayed by Shia LaBeouf in the first three films in the Transformers film series. In early versions of the script, Sam had the nickname "Spike" (the name of the main character in the original Transformers series). This idea was later scrapped because, according to writer Roberto Orci, these nicknames were appropriate for a mechanic and an oil rig worker in the animated series, occupations in which the characters did not work in the film. According to Roberto Orci, the character of Sam was written as a "2007 version of Marty McFly".', ' Fifty years from now, when you''re looking back at your life, don''t you want to be able to say you had the guts to get in the car?'),
	(17, 62, 'Mikaela Banes', 'Mikaela Banes (born 1990) is a beauty with brains, with a penchant for fixing cars, and looks strong enough to make Sam Witwicky offer to "ride" her home in his new car.  She does not seem to mind making out on top of an alien car while other alien cars watch. Kinky.', 'You know, that seat belt thing was a pretty smooth move.'),
	(17, 63, 'Captain Lennox', 'William "Wild Bill" Lennox is a member of the United States Army Rangers.[1] A young, yet capable officer, Lennox has the friendship and trust of the men under his command.  He has a wife and a daughter back home.', 'Listen to me! You''re a soldier now! All right? I need you to take this Cube. Get it into military hands while we hold them off, or a lot of people are gonna die.')

insert PRODUCER (PRODUCER_FIRST_NAME, PRODUCER_LAST_NAME, PRODUCER_BIRTH_DATE)
values
	('Judd', 'Apatow', '1967-12-06'),
	('David', 'Householter', '1961-01-01'),
	('Shauna', 'Robertson', '1975-01-01'),
	('David', 'Russell', '1958-08-20'),
	('Steve', 'Carell','1962-08-16'),
	('Andrew Jay', 'Cohen', null),
	('Jon', 'Poll', '1958-01-01'),
	('Seth', 'Rogan', '1982-04-15'),
	('Clayton', 'Townsend', null),
	('David', 'Lester', null),
	('Liz', 'Glotzer', null),
	('Niki', 'Marvin', '1951-12-01'),
	('Kevin', 'De La Noy', null),
	('Jordan', 'Goldberg', null),
	('Philip', 'Lee', null),
	('Benjamin', 'Melniker', '1913-05-25'),
	('Christopher', 'Nolan', '1970-07-30'),
	('Lorne', 'Orleans', null),
	('Charles', 'Roven', '1949-08-02'),
	('Thomas', 'Tull', null),
	('Michael', 'Uslan', '1950-12-15'),
	('Ross', 'Bell', null),
	('Cean', 'Chaffin', '1957-06-26'),
	('Art', 'Linson', '1942-03-16'),
	('Arnon', 'Milchan', '1941-12-06'),
	('John', 'Dorsey', '1970-02-16'),
	('Wendy', 'Finerman', '1960-08-02'),
	('Charles', 'Newirth', '1955-08-22'),
	('Steve', 'Starkey', null),
	('Steve', 'Tisch', '1949-02-14'),
	('Ian', 'Bryce', '1956-01-01'),
	('Steven', 'Spielberg', '1946-12-18'),
	('Gary', 'Levinsohn', '1959-01-01'),
	('Mark', 'Gordon', '1956-10-10'),
	('Bill', 'Carraro', null),
	('Michael', 'De Luca', '1965-08-13'),
	('Kearie', 'Peak', null),
	('Lawrence', 'Turman', '1926-11-28'),
	('Brian', 'Witten', null),
	('Peter', 'Abrams', null),
	('Cale', 'Boyter', null),
	('Richard', 'Brener', '1972-04-14'),
	('Toby', 'Emmerich', '1963-02-08'),
	('Guy', 'Riedel', null),
	('Stuart', 'Cornfeld', '1952-11-13'),
	('Joel', 'Gallen', '1957-09-29'),
	('Scott', 'Rudin', '1958-07-14'),
	('Adam', 'Schroeder', null),
	('Ben', 'Stiller', '1965-11-30'),
	('Lauren', 'Zalaznick', null),
	('Rhoades', 'Rader', null),
	('Mary', 'McLaglen', '1959-05-27'),
	('George', 'Lucas', '1944-05-14'),
	('Rick', 'McCallum', '1950-08-22'),
	('Joel', 'Silver', '1952-07-14'),
	('Bruce', 'Berman', '1952-04-25'),
	('Grant', 'Hill', null),
	('Andrew', 'Mason', null),
	('Lilly', 'Wachowski', '1967-12-29'),
	('Lana', 'Wachowski', '1965-06-21'),
	('Avi', 'Arad', '1948-08-01'),
	('Stan', 'Lee', '1922-12-28'),
	('Kevin', 'Feige', '1973-06-02'),
	('Jeffrey', 'Katzenberg', '1950-12-21'),
	('David', 'Lipman', null),
	('Aron', 'Warner', null),
	('Mel', 'Gibson', '1956-01-03'),
	('Bruce', 'Davey', null),
	('Steven', 'McEveety', '1954-11-04'),
	('Michael', 'Bay', '1965-02-17'),
	('Ian', 'Bryce', '1956-01-01')


insert 
	FILM_2_PRODUCER (FILM_ID, PRODUCER_ID)
values
	(1,1), 
	(1,2), 
	(1,3), 
	(1,4), 
	(2,1), 
	(2,5), 
	(2,6), 
	(2,3), 
	(2,8), 
	(2,9), 
	(3,10), 
	(3,11), 
	(3,12),
	(4,13), 
	(4,14), 
	(4,15), 
	(4,16), 
	(4,17), 
	(4,18), 
	(4,19), 
	(4,20), 
	(4,21),
	(5,22), 
	(5,23), 
	(5,24), 
	(5,25), 
	(5,26),
	(6,27), 
	(6,28), 
	(6,29), 
	(6,30),
	(7,13), 
	(7,31), 
	(7,32), 
	(7,33), 
	(7,34),
	(8,30), 
	(8,35), 
	(8,36), 
	(8,37), 
	(8,38), 
	(8,39),
	(9,40), 
	(9,41), 
	(9,42), 
	(9,43), 
	(9,44),
	(10,45), 
	(10,46), 
	(10,47), 
	(10,48), 
	(10,49), 
	(10,50),
	(11,45),
	(11,52), 
	(11,51), 
	(11,49),
	(12,53),
	(12,54),
	(13,55),
	(13,56),
	(13,57),
	(13,58),
	(13,59),
	(13,60),
	(14,61),
	(14,62),
	(14,63),
	(15,64),
	(15,65),
	(15,66),
	(16,67),
	(16,68),
	(16,69),
	(17,70),
	(17,32),
	(17,71)